AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless starter - sample API (REST API)

Resources:
  SampleApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sample-api
      CodeUri: src/
      Handler: xyz.handler
      Runtime: python3.12
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  SampleApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/sample-api
      RetentionInDays: 14

Outputs:
  ApiUrl:
    Description: Your API base URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"